// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	productpb "go-ecom-admin/proto/product"

	mock "github.com/stretchr/testify/mock"
)

// MockProductClient is an autogenerated mock type for the ProductClient type
type MockProductClient struct {
	mock.Mock
}

type MockProductClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProductClient) EXPECT() *MockProductClient_Expecter {
	return &MockProductClient_Expecter{mock: &_m.Mock}
}

// DeductStock provides a mock function with given fields: ctx, productID, quantity
func (_m *MockProductClient) DeductStock(ctx context.Context, productID uint64, quantity int32) (*productpb.DeductStockResponse, error) {
	ret := _m.Called(ctx, productID, quantity)

	if len(ret) == 0 {
		panic("no return value specified for DeductStock")
	}

	var r0 *productpb.DeductStockResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64, int32) (*productpb.DeductStockResponse, error)); ok {
		return rf(ctx, productID, quantity)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64, int32) *productpb.DeductStockResponse); ok {
		r0 = rf(ctx, productID, quantity)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*productpb.DeductStockResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64, int32) error); ok {
		r1 = rf(ctx, productID, quantity)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProductClient_DeductStock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeductStock'
type MockProductClient_DeductStock_Call struct {
	*mock.Call
}

// DeductStock is a helper method to define mock.On call
//   - ctx context.Context
//   - productID uint64
//   - quantity int32
func (_e *MockProductClient_Expecter) DeductStock(ctx interface{}, productID interface{}, quantity interface{}) *MockProductClient_DeductStock_Call {
	return &MockProductClient_DeductStock_Call{Call: _e.mock.On("DeductStock", ctx, productID, quantity)}
}

func (_c *MockProductClient_DeductStock_Call) Run(run func(ctx context.Context, productID uint64, quantity int32)) *MockProductClient_DeductStock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64), args[2].(int32))
	})
	return _c
}

func (_c *MockProductClient_DeductStock_Call) Return(_a0 *productpb.DeductStockResponse, _a1 error) *MockProductClient_DeductStock_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProductClient_DeductStock_Call) RunAndReturn(run func(context.Context, uint64, int32) (*productpb.DeductStockResponse, error)) *MockProductClient_DeductStock_Call {
	_c.Call.Return(run)
	return _c
}

// RestoreStock provides a mock function with given fields: ctx, productID, quantity
func (_m *MockProductClient) RestoreStock(ctx context.Context, productID uint64, quantity int32) error {
	ret := _m.Called(ctx, productID, quantity)

	if len(ret) == 0 {
		panic("no return value specified for RestoreStock")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64, int32) error); ok {
		r0 = rf(ctx, productID, quantity)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockProductClient_RestoreStock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RestoreStock'
type MockProductClient_RestoreStock_Call struct {
	*mock.Call
}

// RestoreStock is a helper method to define mock.On call
//   - ctx context.Context
//   - productID uint64
//   - quantity int32
func (_e *MockProductClient_Expecter) RestoreStock(ctx interface{}, productID interface{}, quantity interface{}) *MockProductClient_RestoreStock_Call {
	return &MockProductClient_RestoreStock_Call{Call: _e.mock.On("RestoreStock", ctx, productID, quantity)}
}

func (_c *MockProductClient_RestoreStock_Call) Run(run func(ctx context.Context, productID uint64, quantity int32)) *MockProductClient_RestoreStock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64), args[2].(int32))
	})
	return _c
}

func (_c *MockProductClient_RestoreStock_Call) Return(_a0 error) *MockProductClient_RestoreStock_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProductClient_RestoreStock_Call) RunAndReturn(run func(context.Context, uint64, int32) error) *MockProductClient_RestoreStock_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockProductClient creates a new instance of MockProductClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProductClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProductClient {
	mock := &MockProductClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
