// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	model "go-ecom-admin/internal/order/model"

	mock "github.com/stretchr/testify/mock"

	repository "go-ecom-admin/internal/order/repository"
)

// MockOutboxRepository is an autogenerated mock type for the OutboxRepository type
type MockOutboxRepository struct {
	mock.Mock
}

type MockOutboxRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOutboxRepository) EXPECT() *MockOutboxRepository_Expecter {
	return &MockOutboxRepository_Expecter{mock: &_m.Mock}
}

// CancelWithOutbox provides a mock function with given fields: ctx, orderID, from, to, messages
func (_m *MockOutboxRepository) CancelWithOutbox(ctx context.Context, orderID uint64, from string, to string, messages []*model.OutboxMessage) error {
	ret := _m.Called(ctx, orderID, from, to, messages)

	if len(ret) == 0 {
		panic("no return value specified for CancelWithOutbox")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64, string, string, []*model.OutboxMessage) error); ok {
		r0 = rf(ctx, orderID, from, to, messages)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockOutboxRepository_CancelWithOutbox_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelWithOutbox'
type MockOutboxRepository_CancelWithOutbox_Call struct {
	*mock.Call
}

// CancelWithOutbox is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID uint64
//   - from string
//   - to string
//   - messages []*model.OutboxMessage
func (_e *MockOutboxRepository_Expecter) CancelWithOutbox(ctx interface{}, orderID interface{}, from interface{}, to interface{}, messages interface{}) *MockOutboxRepository_CancelWithOutbox_Call {
	return &MockOutboxRepository_CancelWithOutbox_Call{Call: _e.mock.On("CancelWithOutbox", ctx, orderID, from, to, messages)}
}

func (_c *MockOutboxRepository_CancelWithOutbox_Call) Run(run func(ctx context.Context, orderID uint64, from string, to string, messages []*model.OutboxMessage)) *MockOutboxRepository_CancelWithOutbox_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64), args[2].(string), args[3].(string), args[4].([]*model.OutboxMessage))
	})
	return _c
}

func (_c *MockOutboxRepository_CancelWithOutbox_Call) Return(_a0 error) *MockOutboxRepository_CancelWithOutbox_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOutboxRepository_CancelWithOutbox_Call) RunAndReturn(run func(context.Context, uint64, string, string, []*model.OutboxMessage) error) *MockOutboxRepository_CancelWithOutbox_Call {
	_c.Call.Return(run)
	return _c
}

// ClaimPending provides a mock function with given fields: ctx, limit
func (_m *MockOutboxRepository) ClaimPending(ctx context.Context, limit int) (*repository.OutboxSession, error) {
	ret := _m.Called(ctx, limit)

	if len(ret) == 0 {
		panic("no return value specified for ClaimPending")
	}

	var r0 *repository.OutboxSession
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (*repository.OutboxSession, error)); ok {
		return rf(ctx, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) *repository.OutboxSession); ok {
		r0 = rf(ctx, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.OutboxSession)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOutboxRepository_ClaimPending_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClaimPending'
type MockOutboxRepository_ClaimPending_Call struct {
	*mock.Call
}

// ClaimPending is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
func (_e *MockOutboxRepository_Expecter) ClaimPending(ctx interface{}, limit interface{}) *MockOutboxRepository_ClaimPending_Call {
	return &MockOutboxRepository_ClaimPending_Call{Call: _e.mock.On("ClaimPending", ctx, limit)}
}

func (_c *MockOutboxRepository_ClaimPending_Call) Run(run func(ctx context.Context, limit int)) *MockOutboxRepository_ClaimPending_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockOutboxRepository_ClaimPending_Call) Return(_a0 *repository.OutboxSession, _a1 error) *MockOutboxRepository_ClaimPending_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOutboxRepository_ClaimPending_Call) RunAndReturn(run func(context.Context, int) (*repository.OutboxSession, error)) *MockOutboxRepository_ClaimPending_Call {
	_c.Call.Return(run)
	return _c
}

// CountPending provides a mock function with given fields: ctx
func (_m *MockOutboxRepository) CountPending(ctx context.Context) (int64, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CountPending")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (int64, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) int64); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOutboxRepository_CountPending_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountPending'
type MockOutboxRepository_CountPending_Call struct {
	*mock.Call
}

// CountPending is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockOutboxRepository_Expecter) CountPending(ctx interface{}) *MockOutboxRepository_CountPending_Call {
	return &MockOutboxRepository_CountPending_Call{Call: _e.mock.On("CountPending", ctx)}
}

func (_c *MockOutboxRepository_CountPending_Call) Run(run func(ctx context.Context)) *MockOutboxRepository_CountPending_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockOutboxRepository_CountPending_Call) Return(_a0 int64, _a1 error) *MockOutboxRepository_CountPending_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOutboxRepository_CountPending_Call) RunAndReturn(run func(context.Context) (int64, error)) *MockOutboxRepository_CountPending_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOutboxRepository creates a new instance of MockOutboxRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOutboxRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOutboxRepository {
	mock := &MockOutboxRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
